---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: 8700f49f5d83080be84a1d4f150ef375038f61fed8ea00bf1ee38478d3c35413
      REQ_URL_MAP: "${{toJSON('{\"SL_RESULT_API_HOST\":\"http://3a5e-103-163-248-32.ngrok.io/resultapi/v1\"\
        ,\"SL_API_HOST\":\"http://c0a0-103-163-248-32.ngrok.io/shiftleftapi\",\"SL_RESULTPARSER_API_HOST\"\
        :\"http://67aa-103-163-248-32.ngrok.io/resultparserapi/v1\"}')}}"
    steps:
    - name: Retrieve Scan Info
      id: auth_token
      run: "respJson=$(curl --location --request GET 'http://c0a0-103-163-248-32.ngrok.io/shiftleftapi/scan-info?app_id=${{\
        \ env.APP_ID }}'  --header 'Authorization: Bearer ${{secrets.CLI_ACCESS_TOKEN}}'\
        \  --data-raw ' ' )\necho \"::set-output name=authTokenJson::$respJson\""
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -q --batch-mode --update-snapshots verify
    - name: Scan Initiated
      id: sec_scan_init
      run: "docker login --username  ${{fromJson(steps.auth_token.outputs.authTokenJson).user}}\
        \ --password ${{fromJson(steps.auth_token.outputs.authTokenJson).password}}\
        \ ${{fromJson(steps.auth_token.outputs.authTokenJson).proxyUrl}}\ndocker pull\
        \ -q ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}}\ndocker\
        \ run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/workdir\
        \ -v /var/run/docker.sock:/var/run/docker.sock ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}}\
        \ -access_tkn ${{secrets.CLI_ACCESS_TOKEN}} -app_id ${{ env.APP_ID }} -req_url_map\
        \ ${{ env.REQ_URL_MAP }} event:${{ github.event_name }}  pr_number:${{ github.event.number\
        \ }}"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: "${{github.workspace}}/results/result.sarif"
      if: hashFiles('**/result.sarif') !=''
    - name: Evaluate build status
      run: "cat ${{github.workspace}}/results/status.txt\nexit 1\n"
      if: hashFiles('**/status.txt') !=''
    runs-on: ubuntu-latest
