---
name: Shiftleft Scan
on:
  pull_request:
    branches:
    - Demo
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
jobs:
  scanning:
    env:
      APP_ID: 11b2594106e2e5a5cda520ce351b50960f9625bf121c9914e41061019fbfda37
      BRANCH_NAME: Demo
      SCAN_ID: f80ef3d015035f5d3ec0d4949fa3a65ddc803adbe6eba920fd56484dbb780a4a
      REQ_URL_MAP: "${{toJSON('{\"SL_RESULT_API_HOST\":\"https://42b9-103-163-248-176.ngrok.io/resultapi\"\
        ,\"SL_RESULTPARSER_API_HOST\":\"https://abb5-103-163-248-176.ngrok.io/resultparserapi\"\
        }')}}"
    steps:
    - name: Retrieve Token Info
      id: auth_token
      run: "respJson=$(curl --location --request GET 'https://42b9-103-163-248-176.ngrok.io/resultapi/aws/ecr/token'\
        \  --header 'Authorization: Bearer ${{secrets.CLI_ACCESS_TOKEN}}'  --data-raw\
        \ ' ' )\necho \"::set-output name=authTokenJson::$respJson\""
    - uses: actions/checkout@v2
    - name: Scan Initiated
      id: sec_scan_init
      run: "usrVal=$(echo '${{fromJson(steps.auth_token.outputs.authTokenJson).user}}'\
        \ | openssl enc -aes-256-cbc -d -a -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}}\
        \ ) \nusrPassword=$(echo '${{fromJson(steps.auth_token.outputs.authTokenJson).password}}'\
        \ | openssl enc -aes-256-cbc -d -base64 -A -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}}\
        \ ) \nusrPrxyUrl=$(echo '${{fromJson(steps.auth_token.outputs.authTokenJson).proxyUrl}}'\
        \ | openssl enc -aes-256-cbc -d -a -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}}\
        \ ) \nusrImgTag=$(echo '${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}}'\
        \ | openssl enc -aes-256-cbc -d -a -K ${{secrets.ENC_KEY}} -iv ${{secrets.ENC_IV}}\
        \ ) \ndocker login --username  $usrVal --password $usrPassword $usrPrxyUrl\
        \ \ndocker pull -q $usrImgTag \ndocker run -v ${{github.workspace}}:/src \
        \ --volume ${{github.workspace}}:/workdir -v /var/run/docker.sock:/var/run/docker.sock\
        \ $usrImgTag -access_tkn ${{secrets.CLI_ACCESS_TOKEN}} -app_id ${{ env.APP_ID\
        \ }} -scan_id ${{ env.SCAN_ID }} -branch_name ${{ env.BRANCH_NAME }} -req_url_map\
        \ ${{ env.REQ_URL_MAP }} -tool_name github event:${{ github.event_name }}\
        \  pr_number:${{ github.event.number }}"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: "${{github.workspace}}/results/result.sarif"
      if: hashFiles('**/result.sarif') !=''
    - name: Evaluate build status
      run: "cat ${{github.workspace}}/results/status.txt\nexit 1\n"
      if: hashFiles('**/status.txt') !=''
    runs-on: ubuntu-latest
